/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import controle.ControladorCadastroMaestros;
import entidade.Maestro;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author guilh
 */
public class JanelaCadastroMaestros extends javax.swing.JFrame {

    /**
     * Creates new form JanelaCadastroMaestro
     */
    ControladorCadastroMaestros controlador;
    Maestro[] maestros_cadastrados;

    public JanelaCadastroMaestros(ControladorCadastroMaestros controlador) {
        this.controlador = controlador;
        maestros_cadastrados = Maestro.getVisões();
        initComponents();
        limparCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private Maestro obterMaestroInformado() {
        String nome = nomeTextField.getText();
        if (nome.isEmpty()) {
            return null;
        }
        String anos_experiencia_str = anos_experienciaTextField.getText();
        if (anos_experiencia_str.isEmpty()) {
            return null;
        }
        int anos_experiencia = Integer.parseInt(anos_experiencia_str);
        String estilo_regencia = estilo_regenciaTextField.getText();
        if (estilo_regencia.isEmpty()) {
            return null;
        }
        boolean estrangeiro = estrangeiroCheckBox.isSelected();
        return new Maestro(nome, anos_experiencia, estilo_regencia, estrangeiro);
    }

    private void limparCampos() {
        nomeTextField.setText("");
        anos_experienciaTextField.setText("");
        estilo_regenciaTextField.setText("");
        estrangeiroCheckBox.setSelected(false);
    }

    private void informarErro(String mensagem) {
        JOptionPane.showMessageDialog(this, mensagem, "Erro", JOptionPane.ERROR_MESSAGE);
    }

    private void informarSucesso(String mensagem) {
        JOptionPane.showMessageDialog(this, mensagem, "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }

    private Maestro getVisãoAlterada(String nome) {
        for (Maestro visão : maestros_cadastrados) {
            if (visão.getNome().equals(nome)) {
                return visão;
            }
        }
        return null;
    }

    private void atualizarComboBox() {
        maestros_cadastrados = Maestro.getVisões();
        maestros_cadastradosComboBox.setModel(new DefaultComboBoxModel(maestros_cadastrados));
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        nomeLabel = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        maestros_cadastradosLabel = new javax.swing.JLabel();
        maestros_cadastradosComboBox = new javax.swing.JComboBox();
        anos_experienciaLabel = new javax.swing.JLabel();
        anos_experienciaTextField = new javax.swing.JTextField();
        estilo_regenciaLabel = new javax.swing.JLabel();
        estilo_regenciaTextField = new javax.swing.JTextField();
        comandosPanel = new javax.swing.JPanel();
        inserirButton = new javax.swing.JButton();
        consultarButton = new javax.swing.JButton();
        alterarButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();
        LimparButton = new javax.swing.JButton();
        estrangeiroCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Maestros");
        setPreferredSize(new java.awt.Dimension(677, 331));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        nomeLabel.setText("Nome: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 172, 0, 0);
        getContentPane().add(nomeLabel, gridBagConstraints);

        nomeTextField.setColumns(50);
        nomeTextField.setPreferredSize(new java.awt.Dimension(556, 22));
        nomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 196;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 4, 0, 0);
        getContentPane().add(nomeTextField, gridBagConstraints);

        maestros_cadastradosLabel.setText("Maestros cadastrados:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(64, 92, 0, 0);
        getContentPane().add(maestros_cadastradosLabel, gridBagConstraints);

        maestros_cadastradosComboBox.setModel(new DefaultComboBoxModel(maestros_cadastrados));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 170;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(66, 4, 0, 0);
        getContentPane().add(maestros_cadastradosComboBox, gridBagConstraints);

        anos_experienciaLabel.setText("Anos de experiência:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 101, 0, 0);
        getContentPane().add(anos_experienciaLabel, gridBagConstraints);

        anos_experienciaTextField.setColumns(50);
        anos_experienciaTextField.setPreferredSize(new java.awt.Dimension(556, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 196;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 4, 0, 0);
        getContentPane().add(anos_experienciaTextField, gridBagConstraints);

        estilo_regenciaLabel.setText("Estilo de regência:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 113, 0, 0);
        getContentPane().add(estilo_regenciaLabel, gridBagConstraints);

        estilo_regenciaTextField.setColumns(50);
        estilo_regenciaTextField.setPreferredSize(new java.awt.Dimension(556, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 196;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 0, 0);
        getContentPane().add(estilo_regenciaTextField, gridBagConstraints);

        inserirButton.setText("Inserir");
        inserirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirMaestro(evt);
            }
        });
        comandosPanel.add(inserirButton);

        consultarButton.setText("Consultar");
        consultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarMaestro(evt);
            }
        });
        comandosPanel.add(consultarButton);

        alterarButton.setText("Alterar");
        alterarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarMaestro(evt);
            }
        });
        comandosPanel.add(alterarButton);

        removerButton.setText("Remover");
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerMaestro(evt);
            }
        });
        comandosPanel.add(removerButton);

        LimparButton.setText("Limpar");
        LimparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparCampos(evt);
            }
        });
        comandosPanel.add(LimparButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 115, 16, 199);
        getContentPane().add(comandosPanel, gridBagConstraints);

        estrangeiroCheckBox.setText("Estrangeiro: ");
        estrangeiroCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 141, 0, 0);
        getContentPane().add(estrangeiroCheckBox, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarMaestro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarMaestro

        Maestro visão = (Maestro) maestros_cadastradosComboBox.getSelectedItem();
        Maestro maestro = null;
        String mensagem_erro = null;
        if (visão != null) {
            maestro = Maestro.buscarMaestro(visão.getNome());
            if (maestro == null) {
                mensagem_erro = "Maestro não encontrado";
            }
        } else {
            mensagem_erro = "Nenhum maestro selecionado";
        }

        if (mensagem_erro == null) {
            nomeTextField.setText(maestro.getNome());
            anos_experienciaTextField.setText(Integer.toString(maestro.getAnos_experiencia()));
            estilo_regenciaTextField.setText(maestro.getEstilo_regencia());
            estrangeiroCheckBox.setSelected(maestro.isEstrangeiro());
        } else {
            informarErro(mensagem_erro);
        }

    }//GEN-LAST:event_consultarMaestro

    private void limparCampos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparCampos
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_limparCampos

    private void inserirMaestro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirMaestro
        // TODO add your handling code here:
        Maestro maestro = obterMaestroInformado();
        //System.out.println("maestro: " + maestro.getNome());
        String mensagem_erro = null;
        if (maestro != null) {
            mensagem_erro = controlador.inserirMaestro(maestro);
            informarSucesso("Maestro inserido com sucesso");
        } else {
            mensagem_erro = "Algum atributo do maestro não foi informado";
        }

        if (mensagem_erro == null) {
            Maestro visão = maestro.getVisão();
            maestros_cadastradosComboBox.addItem(visão);
            maestros_cadastradosComboBox.setSelectedItem(visão);
        } else
            informarErro(mensagem_erro);
    }//GEN-LAST:event_inserirMaestro

    private void alterarMaestro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarMaestro
        // TODO add your handling code here:
        Maestro maestro = obterMaestroInformado();
        String mensagem_erro = null;
        if (maestro != null) {
            mensagem_erro = controlador.alterarMaestro(maestro);
            informarSucesso("Maestro alterado com sucesso");
            atualizarComboBox();
        } else {
            mensagem_erro = "Algum atributo do maestro não foi informado";
        }
        if (mensagem_erro == null) {
            Maestro visão = getVisãoAlterada(maestro.getNome());
            if (visão != null) {
                visão.setAnosExperiencia(maestro.getAnos_experiencia());
                maestros_cadastradosComboBox.updateUI();
                maestros_cadastradosComboBox.setSelectedItem(visão);
            }
        } else
            informarErro(mensagem_erro);
    }//GEN-LAST:event_alterarMaestro

    private void removerMaestro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerMaestro
        // TODO add your handling code here:
        Maestro visão = (Maestro) maestros_cadastradosComboBox.getSelectedItem();
        String mensagem_erro = null;
        if (visão != null) {
            mensagem_erro = controlador.removerMaestro(visão.getNome());
            informarSucesso("Maestro removido com sucesso");
        } else {
            mensagem_erro = "Nenhum maestro selecionado";
        }
        if (mensagem_erro == null) {
            maestros_cadastradosComboBox.removeItem(visão);
            limparCampos();
        } else
            informarErro(mensagem_erro);
    }//GEN-LAST:event_removerMaestro

    private void nomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LimparButton;
    private javax.swing.JButton alterarButton;
    private javax.swing.JLabel anos_experienciaLabel;
    private javax.swing.JTextField anos_experienciaTextField;
    private javax.swing.JPanel comandosPanel;
    private javax.swing.JButton consultarButton;
    private javax.swing.JLabel estilo_regenciaLabel;
    private javax.swing.JTextField estilo_regenciaTextField;
    private javax.swing.JCheckBox estrangeiroCheckBox;
    private javax.swing.JButton inserirButton;
    private javax.swing.JComboBox maestros_cadastradosComboBox;
    private javax.swing.JLabel maestros_cadastradosLabel;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JButton removerButton;
    // End of variables declaration//GEN-END:variables

}
