/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import controle.ControladorCadastroPeçasMusicais;
import entidade.PeçaMusical;
import entidade.PeçaMusical.Gênero;

/**
 *
 * @author guilh
 */
public class JanelaCadastroPeçasMusicais extends javax.swing.JFrame {

    /**
     * Creates new form JanelaCadastroPeçasMusicais
     */
    public static Gênero converteStringParaGênero(String genero_str) {
        switch (genero_str) {
            case "clássico":
                return Gênero.clássico;
            // case "romântico":
            //     return Gênero.romântico;
            // case "jazz":
            //     return Gênero.jazz;
            case "rock":
                return Gênero.rock;
            case "pop":
                return Gênero.pop;
            // case "reggae":
            //     return Gênero.reggae;
            // case "blues":
            //     return Gênero.blues;
            // case "country":
            //     return Gênero.country;
            // case "barroco":
            //     return Gênero.barroco;
            // case "modernismo":
            //     return Gênero.modernismo;
            case "samba":
                return Gênero.samba;
            default:
                return null;
        }
    }

    ControladorCadastroPeçasMusicais controlador;
    PeçaMusical[] peças_musicais_cadastradas;

    public JanelaCadastroPeçasMusicais(ControladorCadastroPeçasMusicais controlador) {
        this.controlador = controlador;
        peças_musicais_cadastradas = PeçaMusical.getVisões();
        initComponents();
        limparCampos();
    }

    private void limparCampos() {
        tituloTextField.setText("");
        compositorTextField.setText("");
        duracaoTextField.setText("");
        gêneroButtonGroup.clearSelection();
        tomTextField.setText("");
    }
    
    private void selecionarGêneroRadioButton(int índice_gênero){
        switch(índice_gênero){
            case 0: rockRadioButton.setSelected(true);
            break;
            case 1: clássicoRadioButton.setSelected(true);
            break;
            case 2: popRadioButton.setSelected(true);
            break;
            case 3: sambaRadioButton.setSelected(true);
            break;
        }
    }

    private void informarErro(String mensagem) {
        JOptionPane.showMessageDialog(this, mensagem, "Erro", JOptionPane.ERROR_MESSAGE);
    }

    private void informarSucesso(String mensagem) {
        JOptionPane.showMessageDialog(this, mensagem, "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }

    private PeçaMusical getVisãoAlterada(String titulo) {
        for (PeçaMusical visão : peças_musicais_cadastradas) {
            if (visão.getTitulo().equals(titulo)) {
                return visão;
            }
        }
        return null;
    }

    private PeçaMusical obterPeçaMusicalInformada() {
        String titulo = tituloTextField.getText();
        if (titulo.isEmpty()) {
            return null;
        }
        String compositor = compositorTextField.getText();
        if (compositor.isEmpty()) {
            return null;
        }
        Gênero gênero = null;
        if (gêneroButtonGroup.getSelection() != null) {
            gênero = Gênero.values()[gêneroButtonGroup.getSelection().getMnemonic()];
        }else{
            return null;
        }
        String duracao_str = duracaoTextField.getText();
        if (duracao_str.isEmpty()) {
            return null;
        }
        int duracao = Integer.parseInt(duracao_str);
        String tom = tomTextField.getText();
        if (tom.isEmpty()) {
            return null;
        }
        return new PeçaMusical(titulo, compositor, duracao, tom, gênero);
    }

      private void atualizarComboBox() {
        peças_musicais_cadastradas = PeçaMusical.getVisões();
        peças_musicais_cadastradasComboBox.setModel(new DefaultComboBoxModel(peças_musicais_cadastradas));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        gêneroButtonGroup = new javax.swing.ButtonGroup();
        peças_musicais_cadastradasLabel = new javax.swing.JLabel();
        peças_musicais_cadastradasComboBox = new javax.swing.JComboBox();
        tituloLabel = new javax.swing.JLabel();
        compositorLabel = new javax.swing.JLabel();
        generoLabel = new javax.swing.JLabel();
        duracaoLabel = new javax.swing.JLabel();
        tomLabel = new javax.swing.JLabel();
        tomTextField = new javax.swing.JTextField();
        tituloTextField = new javax.swing.JTextField();
        compositorTextField = new javax.swing.JTextField();
        duracaoTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        cadastrarButton = new javax.swing.JButton();
        consultarButton = new javax.swing.JButton();
        alterarButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();
        limparButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rockRadioButton = new javax.swing.JRadioButton();
        clássicoRadioButton = new javax.swing.JRadioButton();
        popRadioButton = new javax.swing.JRadioButton();
        sambaRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Peças");
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        peças_musicais_cadastradasLabel.setText("Peças musicais cadastradas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 35, 0, 0);
        getContentPane().add(peças_musicais_cadastradasLabel, gridBagConstraints);

        peças_musicais_cadastradasComboBox.setModel(new DefaultComboBoxModel(peças_musicais_cadastradas));
        peças_musicais_cadastradasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peças_musicais_cadastradasComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(55, 14, 0, 0);
        getContentPane().add(peças_musicais_cadastradasComboBox, gridBagConstraints);

        tituloLabel.setText("Título:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 150, 0, 0);
        getContentPane().add(tituloLabel, gridBagConstraints);

        compositorLabel.setText("Compositor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 120, 0, 0);
        getContentPane().add(compositorLabel, gridBagConstraints);

        generoLabel.setText("Gênero:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 135, 0, 0);
        getContentPane().add(generoLabel, gridBagConstraints);

        duracaoLabel.setText("Duração:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 135, 0, 0);
        getContentPane().add(duracaoLabel, gridBagConstraints);

        tomLabel.setText("Tom:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 155, 0, 0);
        getContentPane().add(tomLabel, gridBagConstraints);

        tomTextField.setColumns(50);
        tomTextField.setPreferredSize(new java.awt.Dimension(556, 22));
        tomTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 207;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 8, 0, 0);
        getContentPane().add(tomTextField, gridBagConstraints);

        tituloTextField.setColumns(50);
        tituloTextField.setPreferredSize(new java.awt.Dimension(556, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 207;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 8, 0, 0);
        getContentPane().add(tituloTextField, gridBagConstraints);

        compositorTextField.setColumns(50);
        compositorTextField.setPreferredSize(new java.awt.Dimension(556, 22));
        compositorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compositorTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 207;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 8, 0, 0);
        getContentPane().add(compositorTextField, gridBagConstraints);

        duracaoTextField.setColumns(50);
        duracaoTextField.setPreferredSize(new java.awt.Dimension(556, 22));
        duracaoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duracaoTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 207;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 8, 0, 0);
        getContentPane().add(duracaoTextField, gridBagConstraints);

        cadastrarButton.setText("Cadastrar");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirPeçaMusical(evt);
            }
        });
        jPanel1.add(cadastrarButton);

        consultarButton.setText("Consultar");
        consultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarPeçaMusical(evt);
            }
        });
        jPanel1.add(consultarButton);

        alterarButton.setText("Alterar");
        alterarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarPeçaMusical(evt);
            }
        });
        jPanel1.add(alterarButton);

        removerButton.setText("Remover");
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerPeçaMusical(evt);
            }
        });
        jPanel1.add(removerButton);

        limparButton.setText("Limpar");
        limparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparCampos(evt);
            }
        });
        jPanel1.add(limparButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 45, 42, 76);
        getContentPane().add(jPanel1, gridBagConstraints);

        gêneroButtonGroup.add(rockRadioButton);
        rockRadioButton.setText("rock");
        rockRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rockRadioButtonActionPerformed(evt);
            }
        });
        jPanel2.add(rockRadioButton);

        gêneroButtonGroup.add(clássicoRadioButton);
        clássicoRadioButton.setMnemonic('\u0001');
        clássicoRadioButton.setText("clássico");
        jPanel2.add(clássicoRadioButton);

        gêneroButtonGroup.add(popRadioButton);
        popRadioButton.setMnemonic('\u0002');
        popRadioButton.setText("pop");
        jPanel2.add(popRadioButton);

        gêneroButtonGroup.add(sambaRadioButton);
        sambaRadioButton.setMnemonic('\u0003');
        sambaRadioButton.setText("samba");
        jPanel2.add(sambaRadioButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 1, 6, 0);
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inserirPeçaMusical(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirPeçaMusical
        PeçaMusical peça_musical = obterPeçaMusicalInformada();
        System.out.println(peça_musical);
        String mensagem_erro = null;
        if (peça_musical != null) {
            mensagem_erro = controlador.inserirPeçaMusical(peça_musical);
            informarSucesso("Peça musical inserida com sucesso");

        } else {
            mensagem_erro = "Preencha todos os campos";
        }

        if (mensagem_erro == null) {
            PeçaMusical visão = peça_musical.getVisão();
            peças_musicais_cadastradasComboBox.addItem(visão);
            peças_musicais_cadastradasComboBox.setSelectedItem(visão);
        } else {
            informarErro(mensagem_erro);
        }
    }//GEN-LAST:event_inserirPeçaMusical

    private void consultarPeçaMusical(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarPeçaMusical
        PeçaMusical visão = (PeçaMusical) peças_musicais_cadastradasComboBox.getSelectedItem();
        PeçaMusical peça_musical = null;
        String mensagem_erro = null;
        if (visão != null) {
            peça_musical = PeçaMusical.buscarPeçaMusical(visão.getTitulo());
            if (peça_musical == null) {
                mensagem_erro = "Peça musical não encontrada";
            }
        } else {
            mensagem_erro = "Selecione uma peça musical, nenhuma foi selecionada";
        }

        if (mensagem_erro == null) {
            tituloTextField.setText(peça_musical.getTitulo());
            compositorTextField.setText(peça_musical.getCompositor());
            selecionarGêneroRadioButton(peça_musical.getGênero().ordinal());
            duracaoTextField.setText(Integer.toString(peça_musical.getDuracao()));
            tomTextField.setText(peça_musical.getTom());
        } else {
            informarErro(mensagem_erro);
        }
    }//GEN-LAST:event_consultarPeçaMusical

    private void alterarPeçaMusical(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarPeçaMusical
        PeçaMusical peça_musical = obterPeçaMusicalInformada();
        String mensagem_erro = null;
        if (peça_musical != null) {
            mensagem_erro = controlador.alterarPeçaMusical(peça_musical);
            informarSucesso("Peça musical alterada com sucesso");
            atualizarComboBox();
        } else {
            mensagem_erro = "Preencha todos os campos";
        }

        if (mensagem_erro == null) {
            PeçaMusical visão = getVisãoAlterada(peça_musical.getTitulo());
            if (visão != null) {
                visão.setTom(peça_musical.getTom());
                peças_musicais_cadastradasComboBox.updateUI();
                peças_musicais_cadastradasComboBox.setSelectedItem(visão);
            }
        } else {
            informarErro(mensagem_erro);
        }
    }//GEN-LAST:event_alterarPeçaMusical

    private void removerPeçaMusical(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerPeçaMusical
        PeçaMusical visão = (PeçaMusical) peças_musicais_cadastradasComboBox.getSelectedItem();
        String mensagem_erro = null;
        if (visão != null) {
            mensagem_erro = controlador.removerPeçaMusical(visão.getTitulo());
            informarSucesso("Peça musical removida com sucesso");
        } else {
            mensagem_erro = "Selecione uma peça musical, nenhuma foi selecionada";
        }

        if (mensagem_erro == null) {
            peças_musicais_cadastradasComboBox.removeItem(visão);
            limparCampos();
        } else {
            informarErro(mensagem_erro);
        }
    }//GEN-LAST:event_removerPeçaMusical

    private void limparCampos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparCampos
        limparCampos();
    }//GEN-LAST:event_limparCampos

    private void peças_musicais_cadastradasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peças_musicais_cadastradasComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peças_musicais_cadastradasComboBoxActionPerformed

    private void tomTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tomTextFieldActionPerformed

    private void compositorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compositorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compositorTextFieldActionPerformed

    private void duracaoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duracaoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duracaoTextFieldActionPerformed

    private void rockRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rockRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rockRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarButton;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JRadioButton clássicoRadioButton;
    private javax.swing.JLabel compositorLabel;
    private javax.swing.JTextField compositorTextField;
    private javax.swing.JButton consultarButton;
    private javax.swing.JLabel duracaoLabel;
    private javax.swing.JTextField duracaoTextField;
    private javax.swing.JLabel generoLabel;
    private javax.swing.ButtonGroup gêneroButtonGroup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton limparButton;
    private javax.swing.JComboBox peças_musicais_cadastradasComboBox;
    private javax.swing.JLabel peças_musicais_cadastradasLabel;
    private javax.swing.JRadioButton popRadioButton;
    private javax.swing.JButton removerButton;
    private javax.swing.JRadioButton rockRadioButton;
    private javax.swing.JRadioButton sambaRadioButton;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JTextField tituloTextField;
    private javax.swing.JLabel tomLabel;
    private javax.swing.JTextField tomTextField;
    // End of variables declaration//GEN-END:variables
}
