package interfaces;

import controle.ControladorCadastroInterpretaçõesRepertório;
import javax.swing.DefaultListModel;

import controle.ControladorCadastroRepertórios;
import entidade.Interpretação;
import entidade.Repertório;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
// import com.google.protobuf.TextFormat.ParseException;

public class JanelaCadastroRepertórios extends javax.swing.JFrame {

    ControladorCadastroRepertórios controlador;
    Repertório repertórios_cadastrados[];
    DefaultListModel modelo_interpretações_repertório;

    public JanelaCadastroRepertórios(ControladorCadastroRepertórios controlador) {
        this.controlador = controlador;
        repertórios_cadastrados = Repertório.getVisões();
        initComponents();
        modelo_interpretações_repertório = (DefaultListModel) peças_musicaisList.getModel();
        limparCampos();
    }

    private void limparCampos() {
        sequencialTextField.setText("");
        nomeTextField.setText("");
        data_montagemTextField.setText("");
        descriçãoTextArea.setText("");
        modelo_interpretações_repertório.clear();
    }

    private Repertório obtemRepertórioInformado() {
        String sequencial_str = sequencialTextField.getText();
        int sequencial = 0;
        if (!sequencial_str.isEmpty()) {
            sequencial = Integer.parseInt(sequencial_str);
        }
        String nome = nomeTextField.getText();
        if (nome.isEmpty()) {
            return null;
        }
          String data_montagem_str = data_montagemTextField.getText();
        if (data_montagem_str.isEmpty()) {
            return null;
        }
        Date data_montagem = null;
        try {
            // Ajustar o formato da data para "dd/MM/yyyy"
            data_montagem = new Date(new SimpleDateFormat("dd/MM/yyyy").parse(data_montagem_str).getTime());
        } catch (ParseException e) {
            e.printStackTrace();
            return null;
        }
        String descrição = descriçãoTextArea.getText();
        if (descrição.isEmpty()) {
            return null;
        }
        return new Repertório(sequencial, nome, data_montagem, descrição);
    }

    private void informarErro(String mensagem) {
        JOptionPane.showMessageDialog(this, mensagem, "Erro", JOptionPane.ERROR_MESSAGE);
    }

    private void informarSucesso(String mensagem) {
        JOptionPane.showMessageDialog(this, mensagem, "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }

    private Repertório getVisãoAlterada(int sequencial) {
        for (Repertório visão : repertórios_cadastrados) {
            if (visão.getSequencial() == sequencial) {
                return visão;
            }
        }
        return null;
    }

    public void atualizarListaInterpretaçõesRepertório(int sequencial) {
        modelo_interpretações_repertório.clear();
        Interpretação[] interpretações_repertório = Interpretação.buscarInterpretaçõesRepertório(sequencial);
        for (Interpretação interpretação : interpretações_repertório) {
            modelo_interpretações_repertório.addElement(interpretação);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        repertóriosCadastrados = new javax.swing.JLabel();
        repertórios_cadastradosComboBox = new javax.swing.JComboBox();
        sequencialLabel = new javax.swing.JLabel();
        sequencialTextField = new javax.swing.JTextField();
        nomeLabel = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        data_montagemLabel = new javax.swing.JLabel();
        data_montagemTextField = new javax.swing.JTextField();
        descriçãoLabel = new javax.swing.JLabel();
        peças_musicaisLabel = new javax.swing.JLabel();
        comandosPanel = new javax.swing.JPanel();
        inserirButton = new javax.swing.JButton();
        consultarButton = new javax.swing.JButton();
        alterarButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();
        interpretaçõesButton = new javax.swing.JButton();
        limparButton = new javax.swing.JButton();
        peças_musicaisScrollPane = new javax.swing.JScrollPane();
        peças_musicaisList = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriçãoTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        repertóriosCadastrados.setText("Repertórios:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 112, 0, 0);
        getContentPane().add(repertóriosCadastrados, gridBagConstraints);

        repertórios_cadastradosComboBox.setModel(new DefaultComboBoxModel(repertórios_cadastrados));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 139;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 12, 0, 0);
        getContentPane().add(repertórios_cadastradosComboBox, gridBagConstraints);

        sequencialLabel.setText("Identificador Sequencial:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 45, 0, 0);
        getContentPane().add(sequencialLabel, gridBagConstraints);

        sequencialTextField.setEditable(false);
        sequencialTextField.setColumns(50);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        getContentPane().add(sequencialTextField, gridBagConstraints);

        nomeLabel.setText("Nome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 135, 0, 0);
        getContentPane().add(nomeLabel, gridBagConstraints);

        nomeTextField.setColumns(50);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        getContentPane().add(nomeTextField, gridBagConstraints);

        data_montagemLabel.setText("Data de montagem:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 70, 0, 0);
        getContentPane().add(data_montagemLabel, gridBagConstraints);

        data_montagemTextField.setColumns(50);
        data_montagemTextField.setText("DD/MM/AAAA");
        data_montagemTextField.setToolTipText("DD/MM/AAAA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        getContentPane().add(data_montagemTextField, gridBagConstraints);

        descriçãoLabel.setText("Descrição:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 122, 0, 0);
        getContentPane().add(descriçãoLabel, gridBagConstraints);

        peças_musicaisLabel.setText("Peças musicais no repertório:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 22, 0, 0);
        getContentPane().add(peças_musicaisLabel, gridBagConstraints);

        inserirButton.setText("Inserir");
        inserirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirRepertório(evt);
            }
        });
        comandosPanel.add(inserirButton);

        consultarButton.setText("Consultar");
        consultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarRepertório(evt);
            }
        });
        comandosPanel.add(consultarButton);

        alterarButton.setText("Alterar");
        alterarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarRepertório(evt);
            }
        });
        comandosPanel.add(alterarButton);

        removerButton.setText("Remover");
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerRepertório(evt);
            }
        });
        comandosPanel.add(removerButton);

        interpretaçõesButton.setText("Interpretações");
        interpretaçõesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarInterpretações(evt);
            }
        });
        comandosPanel.add(interpretaçõesButton);

        limparButton.setText("Limpar");
        limparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparCampos(evt);
            }
        });
        comandosPanel.add(limparButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.ipady = 39;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 6, 28);
        getContentPane().add(comandosPanel, gridBagConstraints);

        peças_musicaisList.setModel(new DefaultListModel());
        peças_musicaisList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        peças_musicaisList.setVisibleRowCount(4);
        peças_musicaisScrollPane.setViewportView(peças_musicaisList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 333;
        gridBagConstraints.ipady = 44;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 12, 0, 0);
        getContentPane().add(peças_musicaisScrollPane, gridBagConstraints);

        descriçãoTextArea.setColumns(20);
        descriçãoTextArea.setRows(5);
        jScrollPane1.setViewportView(descriçãoTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 333;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarInterpretações(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarInterpretações
        // TODO add your handling code here:
        String sequencial_str = sequencialTextField.getText();
        int sequencial = 0;
        if (!sequencial_str.isEmpty()) {
            sequencial = Integer.parseInt(sequencial_str);
        }
        if (sequencial > 0)
            new ControladorCadastroInterpretaçõesRepertório(this, sequencial);
        else
            informarErro("Nenhum repertório selecionado");
    }//GEN-LAST:event_cadastrarInterpretações

    private void limparCampos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparCampos
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_limparCampos

    private void peças_musicaisButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_peças_musicaisButtonActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_peças_musicaisButtonActionPerformed

    private void inserirRepertório(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_inserirRepertório
        Repertório repertório = obtemRepertórioInformado();
        String mensagem_erro = null;
        if (repertório != null) {
            mensagem_erro = controlador.inserirRepertório(repertório);
            informarSucesso("Repertório inserido com sucesso");
        } else {
            mensagem_erro = "Preencha todos os campos";
        }
        if (mensagem_erro == null) {
            int sequencial = Repertório.últimoSequencial();
            repertório.setSequencial(sequencial);
            Repertório visão = repertório.getVisão();
            repertórios_cadastradosComboBox.addItem(visão);
            repertórios_cadastradosComboBox.setSelectedItem(visão);
            sequencialTextField.setText("" + sequencial);
        } else {
            informarErro(mensagem_erro);
        }
    }// GEN-LAST:event_inserirRepertório

    private void consultarRepertório(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_consultarRepertório
        Repertório visão = (Repertório) repertórios_cadastradosComboBox.getSelectedItem();
        Repertório repertório = null;
        String mensagem_erro = null;
        int sequencial = -1;
        if (visão != null) {
            sequencial = visão.getSequencial();
            repertório = Repertório.buscarRepertório(sequencial);
            if (repertório == null) {
                mensagem_erro = "Repertório não encontrado";
            }
        } else {
            mensagem_erro = "Nenhum repertório selecionado";
        }
        if (mensagem_erro == null) {
            sequencialTextField.setText(sequencial + "");
            nomeTextField.setText(repertório.getNome());
            data_montagemTextField.setText(repertório.getDataMontagemFormatada());
            descriçãoTextArea.setText(repertório.getDescrição());
            atualizarListaInterpretaçõesRepertório(sequencial);
        } else {
            informarErro(mensagem_erro);
        }

    }// GEN-LAST:event_consultarRepertório

    private void alterarRepertório(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_alterarRepertório
        Repertório repertório = obtemRepertórioInformado();
        String mensagem_erro = null;
        if (repertório != null) {
            mensagem_erro = controlador.alterarRepertório(repertório);
            informarSucesso("Repertório alterado com sucesso");
        } else {
            mensagem_erro = "Preencha todos os campos";
        }
        if (mensagem_erro == null) {
            Repertório visão = getVisãoAlterada(repertório.getSequencial());
            if (visão != null) {
                visão.setNome(repertório.getNome());
            }
            repertórios_cadastradosComboBox.updateUI();
            repertórios_cadastradosComboBox.setSelectedItem(visão);
        } else {
            informarErro(mensagem_erro);
        }
    }// GEN-LAST:event_alterarRepertório

    private void removerRepertório(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_removerRepertório
        Repertório visão = (Repertório) repertórios_cadastradosComboBox.getSelectedItem();
        String mensagem_erro = null;
        if (visão != null) {
            mensagem_erro = controlador.removerRepertório(visão.getSequencial());
            informarSucesso("Repertório removido com sucesso");
        } else {
            mensagem_erro = "Nenhum repertório selecionado";
        }
        if (mensagem_erro == null) {
            repertórios_cadastradosComboBox.removeItem(visão);
            limparCampos();
        } else {
            informarErro(mensagem_erro);
        }
    }// GEN-LAST:event_removerRepertório

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarButton;
    private javax.swing.JPanel comandosPanel;
    private javax.swing.JButton consultarButton;
    private javax.swing.JLabel data_montagemLabel;
    private javax.swing.JTextField data_montagemTextField;
    private javax.swing.JLabel descriçãoLabel;
    private javax.swing.JTextArea descriçãoTextArea;
    private javax.swing.JButton inserirButton;
    private javax.swing.JButton interpretaçõesButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limparButton;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JLabel peças_musicaisLabel;
    private javax.swing.JList peças_musicaisList;
    private javax.swing.JScrollPane peças_musicaisScrollPane;
    private javax.swing.JButton removerButton;
    private javax.swing.JLabel repertóriosCadastrados;
    private javax.swing.JComboBox repertórios_cadastradosComboBox;
    private javax.swing.JLabel sequencialLabel;
    private javax.swing.JTextField sequencialTextField;
    // End of variables declaration//GEN-END:variables
}
