package interfaces;

import controle.ControladorCadastroInterpretaçõesRepertório;
import entidade.PeçaMusical;
import entidade.Repertório;
import entidade.Interpretação;
import javax.swing.DefaultComboBoxModel;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class JanelaCadastroInterpretação extends javax.swing.JFrame {

    ControladorCadastroInterpretaçõesRepertório controlador;
    JanelaCadastroRepertórios janela_mãe;
    int sequencial_repertório;
    PeçaMusical[] peças_musicais_cadastradas;
    DefaultListModel modelo_lista_interpretações;

    public JanelaCadastroInterpretação(ControladorCadastroInterpretaçõesRepertório controlador,
            JanelaCadastroRepertórios janela_mãe, int sequencial_repertório) {
        this.controlador = controlador;
        this.janela_mãe = janela_mãe;
        this.sequencial_repertório = sequencial_repertório;
        peças_musicais_cadastradas = PeçaMusical.getVisões();
        initComponents();
        atualizarTítuloRepertório();
        atualizarListaInterpretações();

        // Adiciona um WindowListener para capturar o evento de fechamento da janela
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                janela_mãe.atualizarListaInterpretaçõesRepertório(sequencial_repertório);
            }
        });
    }

    private void atualizarTítuloRepertório() {
        Repertório repertório = Repertório.buscarRepertório(sequencial_repertório);
        repertórioLabel.setText("Repertório: " + repertório.getNome());

    }

    private void atualizarListaInterpretações() {
        modelo_lista_interpretações = (DefaultListModel) peças_musicais_repertorioList.getModel();
        Interpretação[] interpretações_repertório = Interpretação.buscarInterpretaçõesRepertório(sequencial_repertório);
        for (Interpretação interpretação : interpretações_repertório) {
            modelo_lista_interpretações.addElement(interpretação);
        }
    }

    private void informarErro(String mensagem) {
        JOptionPane.showMessageDialog(this, mensagem, "Erro", JOptionPane.ERROR_MESSAGE);
    }

    private void informarSucesso(String mensagem) {
        JOptionPane.showMessageDialog(this, mensagem, "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        peças_musicais_cadastradasLabel = new javax.swing.JLabel();
        peças_musicais_repertorioLabel = new javax.swing.JLabel();
        peças_musicais_repertorioScrollPane = new javax.swing.JScrollPane();
        peças_musicais_repertorioList = new javax.swing.JList();
        peças_musicais_cadastradasComboBox = new javax.swing.JComboBox();
        botoesPanel = new javax.swing.JPanel();
        inserirButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();
        repertórioLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        peças_musicais_cadastradasLabel.setText("Peças musicais cadastradas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 16, 0, 0);
        getContentPane().add(peças_musicais_cadastradasLabel, gridBagConstraints);

        peças_musicais_repertorioLabel.setText("Peças musicais no repertório:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 12, 0, 0);
        getContentPane().add(peças_musicais_repertorioLabel, gridBagConstraints);

        peças_musicais_repertorioList.setModel(new DefaultListModel());
        peças_musicais_repertorioList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        peças_musicais_repertorioScrollPane.setViewportView(peças_musicais_repertorioList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 204;
        gridBagConstraints.ipady = 78;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(36, 12, 0, 0);
        getContentPane().add(peças_musicais_repertorioScrollPane, gridBagConstraints);

        peças_musicais_cadastradasComboBox.setModel(new DefaultComboBoxModel(peças_musicais_cadastradas));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 77;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 0, 0);
        getContentPane().add(peças_musicais_cadastradasComboBox, gridBagConstraints);

        inserirButton.setText("Inserir");
        inserirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirInterpretação(evt);
            }
        });

        removerButton.setText("Remover");
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerInterpretação(evt);
            }
        });

        javax.swing.GroupLayout botoesPanelLayout = new javax.swing.GroupLayout(botoesPanel);
        botoesPanel.setLayout(botoesPanelLayout);
        botoesPanelLayout.setHorizontalGroup(
            botoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoesPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(inserirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(removerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        botoesPanelLayout.setVerticalGroup(
            botoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(botoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inserirButton)
                    .addComponent(removerButton))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 108;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 41, 15, 0);
        getContentPane().add(botoesPanel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 146;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 16, 0, 0);
        getContentPane().add(repertórioLabel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inserirInterpretação(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_inserirInterpretação
        PeçaMusical visão_peça_musical = (PeçaMusical) peças_musicais_cadastradasComboBox.getSelectedItem();
        String mensagem_erro = null;
        Interpretação interpretação = null;
        if (visão_peça_musical != null) {
            Repertório visão_repertório = Repertório.buscarRepertório(sequencial_repertório);
            interpretação = new Interpretação(0, visão_repertório, visão_peça_musical);
            mensagem_erro = controlador.inserirInterpretação(interpretação);
            if (mensagem_erro == null) {
                int sequencial = Interpretação.últimoSequencial();
                interpretação.setSequencial(sequencial);
                modelo_lista_interpretações.addElement(interpretação);
            } else {
                informarErro(mensagem_erro);
            }
        }

    }

    // GEN-LAST:event_inserirInterpretação
    private void removerInterpretação(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_removerInterpretação
        Interpretação interpretação = (Interpretação) peças_musicais_repertorioList.getSelectedValue();
        String mensagem_erro = null;
        if (interpretação != null) {
            mensagem_erro = controlador.removerInterpretação(interpretação.getSequencial());
        }
        if (mensagem_erro == null) {
            modelo_lista_interpretações.removeElement(interpretação);
        } else {
            mensagem_erro = "Nenhuma peça foi selecionada";
        }
        if (mensagem_erro == null) {
            modelo_lista_interpretações.removeElement(interpretação);
        } else {
            informarErro(mensagem_erro);
        }
    }// GEN-LAST:event_removerInterpretação

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botoesPanel;
    private javax.swing.JButton inserirButton;
    private javax.swing.JComboBox peças_musicais_cadastradasComboBox;
    private javax.swing.JLabel peças_musicais_cadastradasLabel;
    private javax.swing.JLabel peças_musicais_repertorioLabel;
    private javax.swing.JList peças_musicais_repertorioList;
    private javax.swing.JScrollPane peças_musicais_repertorioScrollPane;
    private javax.swing.JButton removerButton;
    private javax.swing.JLabel repertórioLabel;
    // End of variables declaration//GEN-END:variables
}
