/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces;

import entidade.PeçaMusicalPopular.EstiloMúsicaPopular;
import entidade.PeçaMusicalPopular.InstrumentaçãoCaracterística;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author guilh
 */
public class PainelPeçaMusicalPopular extends javax.swing.JPanel {

    /**
     * Creates new form PainelPeçaMusicalPopular
     */
    public PainelPeçaMusicalPopular() {
        initComponents();
        limparCampos();
    }

    public EstiloMúsicaPopular getSelectedEstiloMúsicaPopular() {
        Object estilo_música_popular = estilo_música_popularComboBox.getSelectedItem();
        if (estilo_música_popular != null) {
            return (EstiloMúsicaPopular) estilo_música_popular;
        } else {
            return null;
        }
    }

    public void setEstiloMusicaPopular(EstiloMúsicaPopular estilo_música_popular) {
        estilo_música_popularComboBox.setSelectedItem(estilo_música_popular);
    }

    public InstrumentaçãoCaracterística getInstrumentaçãoCaracterística() {
        Object instrumentação_característica = instrumentação_característicaComboBox.getSelectedItem();
        if (instrumentação_característica != null) {
            return (InstrumentaçãoCaracterística) instrumentação_característica;
        } else {
            return null;
        }
    }

    public void setInstrumentaçãoCaracterística(InstrumentaçãoCaracterística instrumentação_característica) {
        instrumentação_característicaComboBox.setSelectedItem(instrumentação_característica);
    }

    public void limparCampos() {
        estilo_música_popularComboBox.setSelectedIndex(-1);
        instrumentação_característicaComboBox.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        estilo_música_popularLabel = new javax.swing.JLabel();
        instrumentação_caraterísticaLabel = new javax.swing.JLabel();
        estilo_música_popularComboBox = new javax.swing.JComboBox();
        instrumentação_característicaComboBox = new javax.swing.JComboBox();

        setLayout(new java.awt.GridBagLayout());

        estilo_música_popularLabel.setText("Estilo música popular:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 78, 0, 0);
        add(estilo_música_popularLabel, gridBagConstraints);

        instrumentação_caraterísticaLabel.setText("Instrumentação característica");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 40, 0, 0);
        add(instrumentação_caraterísticaLabel, gridBagConstraints);

        estilo_música_popularComboBox.setModel(new DefaultComboBoxModel(EstiloMúsicaPopular.values()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(46, 6, 0, 128);
        add(estilo_música_popularComboBox, gridBagConstraints);

        instrumentação_característicaComboBox.setModel(new DefaultComboBoxModel(InstrumentaçãoCaracterística.values()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 198, 128);
        add(instrumentação_característicaComboBox, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox estilo_música_popularComboBox;
    private javax.swing.JLabel estilo_música_popularLabel;
    private javax.swing.JComboBox instrumentação_característicaComboBox;
    private javax.swing.JLabel instrumentação_caraterísticaLabel;
    // End of variables declaration//GEN-END:variables
}
