/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces;

import entidade.PeçaMusicalPopular.EstiloMúsicaPopular;
import entidade.PeçaMusicalPopular.InstrumentaçãoCaracterística;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author guilh
 */
public class PainelPeçaMusicalPopular extends javax.swing.JPanel {

    /**
     * Creates new form PainelPeçaMusicalPopular
     */
    public PainelPeçaMusicalPopular() {
        initComponents();
        limparCampos();
    }

    public EstiloMúsicaPopular getSelectedEstiloMúsicaPopular() {
        Object estilo_música_popular = estilo_música_popularComboBox.getSelectedItem();
        if (estilo_música_popular != null) {
            return (EstiloMúsicaPopular) estilo_música_popular;
        } else {
            return null;
        }
    }

    public void setEstiloMusicaPopular(EstiloMúsicaPopular estilo_música_popular) {
        estilo_música_popularComboBox.setSelectedItem(estilo_música_popular);
    }

    public InstrumentaçãoCaracterística getInstrumentaçãoCaracterística() {
        Object instrumentação_característica = instrumentação_característicaComboBox.getSelectedItem();
        if (instrumentação_característica != null) {
            return (InstrumentaçãoCaracterística) instrumentação_característica;
        } else {
            return null;
        }
    }

    public void setInstrumentaçãoCaracterística(InstrumentaçãoCaracterística instrumentação_característica) {
        instrumentação_característicaComboBox.setSelectedItem(instrumentação_característica);
    }

    public void limparCampos() {
        estilo_música_popularComboBox.setSelectedIndex(-1);
        instrumentação_característicaComboBox.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estilo_música_popularLabel = new javax.swing.JLabel();
        instrumentação_caraterísticaLabel = new javax.swing.JLabel();
        estilo_música_popularComboBox = new javax.swing.JComboBox();
        instrumentação_característicaComboBox = new javax.swing.JComboBox();

        estilo_música_popularLabel.setText("Estilo música popular:");

        instrumentação_caraterísticaLabel.setText("Instrumentação característica");

        estilo_música_popularComboBox.setModel(new DefaultComboBoxModel(EstiloMúsicaPopular.values()));

        instrumentação_característicaComboBox.setModel(new DefaultComboBoxModel(InstrumentaçãoCaracterística.values()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(estilo_música_popularLabel)
                        .addGap(6, 6, 6)
                        .addComponent(estilo_música_popularComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(instrumentação_caraterísticaLabel)
                        .addGap(6, 6, 6)
                        .addComponent(instrumentação_característicaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(estilo_música_popularLabel))
                    .addComponent(estilo_música_popularComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(instrumentação_caraterísticaLabel))
                    .addComponent(instrumentação_característicaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(201, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox estilo_música_popularComboBox;
    private javax.swing.JLabel estilo_música_popularLabel;
    private javax.swing.JComboBox instrumentação_característicaComboBox;
    private javax.swing.JLabel instrumentação_caraterísticaLabel;
    // End of variables declaration//GEN-END:variables
}
