/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces;

import entidade.PeçaMusicalClássica.EstiloMúsicaClássica;

/**
 *
 * @author guilh
 */
public class PainelPeçaMusicalClássica extends javax.swing.JPanel {

    /**
     * Creates new form PainelPeçaMusicalClássica
     */
    public PainelPeçaMusicalClássica() {
        initComponents();
        limparCampos();

    }
    public EstiloMúsicaClássica getSelectedEstiloMúsicaClássica() {
        EstiloMúsicaClássica estilo_música_clássica = null;
        if (estilo_música_clássicaButtonGroup.getSelection() != null) {
            estilo_música_clássica = EstiloMúsicaClássica.values()[estilo_música_clássicaButtonGroup.getSelection().getMnemonic()];
        }
        return estilo_música_clássica;

    }

    public void setEstiloMusicaClássica(int índice_estilo_música_clássica) {
        switch (índice_estilo_música_clássica) {
            case 0:
                barrocoRadioButton.setSelected(true);
                break;
            case 1:
                rômanticoRadioButton.setSelected(true);
                break;
            case 2:
                clássicoRadioButton.setSelected(true);
                break;
            case 3:
                modernismoRadioButton.setSelected(true);
                break;
        }
    }

    public boolean isMuitoConhecida() {
        return muito_conhecidaCheckBox.isSelected();
    }

    public void setMuitoConhecida(boolean muito_conhecida) {
        muito_conhecidaCheckBox.setSelected(muito_conhecida);
    }

    public void limparCampos() {
        estilo_música_clássicaButtonGroup.clearSelection();
        muito_conhecidaCheckBox.setSelected(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estilo_música_clássicaButtonGroup = new javax.swing.ButtonGroup();
        estilo_música_clássicaLabel = new javax.swing.JLabel();
        muito_conhecidaCheckBox = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        barrocoRadioButton = new javax.swing.JRadioButton();
        rômanticoRadioButton = new javax.swing.JRadioButton();
        clássicoRadioButton = new javax.swing.JRadioButton();
        modernismoRadioButton = new javax.swing.JRadioButton();

        estilo_música_clássicaLabel.setText("Estilo música clássica:");

        muito_conhecidaCheckBox.setText("Muito conhecida:");
        muito_conhecidaCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        estilo_música_clássicaButtonGroup.add(barrocoRadioButton);
        barrocoRadioButton.setText("barroco");

        estilo_música_clássicaButtonGroup.add(rômanticoRadioButton);
        rômanticoRadioButton.setMnemonic('\u0001');
        rômanticoRadioButton.setText("rômantico");

        estilo_música_clássicaButtonGroup.add(clássicoRadioButton);
        clássicoRadioButton.setMnemonic('\u0002');
        clássicoRadioButton.setText("clássico");

        estilo_música_clássicaButtonGroup.add(modernismoRadioButton);
        modernismoRadioButton.setMnemonic('\u0003');
        modernismoRadioButton.setText("modernismo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barrocoRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rômanticoRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clássicoRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modernismoRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barrocoRadioButton)
                    .addComponent(rômanticoRadioButton)
                    .addComponent(clássicoRadioButton)
                    .addComponent(modernismoRadioButton))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(estilo_música_clássicaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(muito_conhecidaCheckBox)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estilo_música_clássicaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(muito_conhecidaCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton barrocoRadioButton;
    private javax.swing.JRadioButton clássicoRadioButton;
    private javax.swing.ButtonGroup estilo_música_clássicaButtonGroup;
    private javax.swing.JLabel estilo_música_clássicaLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton modernismoRadioButton;
    private javax.swing.JCheckBox muito_conhecidaCheckBox;
    private javax.swing.JRadioButton rômanticoRadioButton;
    // End of variables declaration//GEN-END:variables
}
