/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces;

import entidade.PeçaMusicalClássica.EstiloMúsicaClássica;

/**
 *
 * @author guilh
 */
public class PainelPeçaMusicalClássica extends javax.swing.JPanel {

    /**
     * Creates new form PainelPeçaMusicalClássica
     */
    public PainelPeçaMusicalClássica() {
        initComponents();
        limparCampos();
    }

    public EstiloMúsicaClássica getSelectedEstiloMúsicaClássica() {
        EstiloMúsicaClássica estilo_música_clássica = null;
        if (estilo_música_clássicaButtonGroup.getSelection() != null) {
            estilo_música_clássica = EstiloMúsicaClássica.values()[estilo_música_clássicaButtonGroup.getSelection().getMnemonic()];
        }
        return estilo_música_clássica;

    }

    public void setEstiloMusicaClássica(int índice_estilo_música_clássica) {
        switch (índice_estilo_música_clássica) {
            case 0:
                barrocoRadioButton.setSelected(true);
                break;
            case 1:
                românticoRadioButton.setSelected(true);
                break;
            case 2:
                clássicoRadioButton.setSelected(true);
                break;
            case 3:
                modernismoRadioButton.setSelected(true);
                break;
        }
    }

    public boolean isMuitoConhecida() {
        return muito_conhecidaCheckBox.isSelected();
    }

    public void setMuitoConhecida(boolean muito_conhecida) {
        muito_conhecidaCheckBox.setSelected(muito_conhecida);
    }

    public void limparCampos() {
        estilo_música_clássicaButtonGroup.clearSelection();
        muito_conhecidaCheckBox.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estilo_música_clássicaButtonGroup = new javax.swing.ButtonGroup();
        estilo_música_clássicaLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        barrocoRadioButton = new javax.swing.JRadioButton();
        românticoRadioButton = new javax.swing.JRadioButton();
        clássicoRadioButton = new javax.swing.JRadioButton();
        modernismoRadioButton = new javax.swing.JRadioButton();
        muito_conhecidaCheckBox = new javax.swing.JCheckBox();

        estilo_música_clássicaLabel.setText("Estilo música clásica:");

        estilo_música_clássicaButtonGroup.add(barrocoRadioButton);
        barrocoRadioButton.setText("barroco");

        estilo_música_clássicaButtonGroup.add(românticoRadioButton);
        românticoRadioButton.setMnemonic('\u0001');
        românticoRadioButton.setText("romântico");
        românticoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                românticoRadioButtonActionPerformed(evt);
            }
        });

        estilo_música_clássicaButtonGroup.add(clássicoRadioButton);
        clássicoRadioButton.setMnemonic('\u0002');
        clássicoRadioButton.setText("clássico");
        clássicoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clássicoRadioButtonActionPerformed(evt);
            }
        });

        estilo_música_clássicaButtonGroup.add(modernismoRadioButton);
        modernismoRadioButton.setMnemonic('\u0003');
        modernismoRadioButton.setText("modernismo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barrocoRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(românticoRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clássicoRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modernismoRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barrocoRadioButton)
                    .addComponent(românticoRadioButton)
                    .addComponent(clássicoRadioButton)
                    .addComponent(modernismoRadioButton))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        muito_conhecidaCheckBox.setText("Muito conhecida:");
        muito_conhecidaCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(estilo_música_clássicaLabel)
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(muito_conhecidaCheckBox))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estilo_música_clássicaLabel)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(muito_conhecidaCheckBox))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void românticoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_românticoRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_românticoRadioButtonActionPerformed

    private void clássicoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clássicoRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clássicoRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton barrocoRadioButton;
    private javax.swing.JRadioButton clássicoRadioButton;
    private javax.swing.ButtonGroup estilo_música_clássicaButtonGroup;
    private javax.swing.JLabel estilo_música_clássicaLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton modernismoRadioButton;
    private javax.swing.JCheckBox muito_conhecidaCheckBox;
    private javax.swing.JRadioButton românticoRadioButton;
    // End of variables declaration//GEN-END:variables
}
