/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces;

import javax.swing.DefaultComboBoxModel;

import entidade.PeçaMusicalPopular.EstiloMúsicaPopular;

/**
 *
 * @author guilh
 */
public class PainelFiltrosPeçaMusicalPopular extends javax.swing.JPanel {

    /**
     * Creates new form PainelFiltrosPeçaMusicalPopular
     */
    public PainelFiltrosPeçaMusicalPopular() {
        initComponents();
        limparFiltros();
    }

    public EstiloMúsicaPopular getEstiloMúsicaPopular(){
      return (EstiloMúsicaPopular) estilo_música_popularComboBox.getSelectedItem();
    }

    public void limparFiltros(){
      estilo_música_popularComboBox.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        estilo_música_popularLabel = new javax.swing.JLabel();
        estilo_música_popularComboBox = new javax.swing.JComboBox();

        setLayout(new java.awt.GridBagLayout());

        estilo_música_popularLabel.setText("Estilo música popular:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 6, 0, 0);
        add(estilo_música_popularLabel, gridBagConstraints);

        estilo_música_popularComboBox.setModel(new DefaultComboBoxModel(EstiloMúsicaPopular.values()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 12, 54, 44);
        add(estilo_música_popularComboBox, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox estilo_música_popularComboBox;
    private javax.swing.JLabel estilo_música_popularLabel;
    // End of variables declaration//GEN-END:variables
}
