/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces;

/**
 *
 * @author guilh
 */
public class PainelFiltrosPeçaMusicalClássica extends javax.swing.JPanel {

    /**
     * Creates new form PainelFiltrosPeçaMusicalClássica
     */
    public PainelFiltrosPeçaMusicalClássica() {
        initComponents();
        limparFiltros();
    }

    public char getMuitoConhecida(){
      char muito_conhecida = 'X';
      if(muito_coinhecidaButtonGroup.getSelection() != null){
        switch (muito_coinhecidaButtonGroup.getSelection().getMnemonic()) {
            case 0: muito_conhecida = 'T'; break;
            case 1: muito_conhecida = 'F'; break;
        }
      }
      return muito_conhecida;
    }

    public void limparFiltros(){
      muito_coinhecidaButtonGroup.clearSelection();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        muito_coinhecidaButtonGroup = new javax.swing.ButtonGroup();
        muito_conhecidaLabel = new javax.swing.JLabel();
        botoesPanel = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setLayout(new java.awt.GridBagLayout());

        muito_conhecidaLabel.setText("Muito conhecida:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 18, 0, 0);
        add(muito_conhecidaLabel, gridBagConstraints);

        muito_coinhecidaButtonGroup.add(jRadioButton1);
        jRadioButton1.setText("Sim");

        muito_coinhecidaButtonGroup.add(jRadioButton2);
        jRadioButton2.setMnemonic('\u0001');
        jRadioButton2.setText("Não");

        javax.swing.GroupLayout botoesPanelLayout = new javax.swing.GroupLayout(botoesPanel);
        botoesPanel.setLayout(botoesPanelLayout);
        botoesPanelLayout.setHorizontalGroup(
            botoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        botoesPanelLayout.setVerticalGroup(
            botoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botoesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(botoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 6, 36, 22);
        add(botoesPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botoesPanel;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.ButtonGroup muito_coinhecidaButtonGroup;
    private javax.swing.JLabel muito_conhecidaLabel;
    // End of variables declaration//GEN-END:variables
}
